name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'

      - name: Build binary
        run: |
          go build -o footballDataApp

      - name: Archive binary
        run: |
          tar -czvf footballDataApp.tar.gz footballDataApp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: footballDataApp
          path: ./footballDataApp.tar.gz

      - name: Build binary for macOS
        run: |
          env GOOS=darwin GOARCH=arm64 go build -o footballDataApp

      - name: Archive binary for macOS
        run: |
          tar -czvf footballDataApp_macos.tar.gz footballDataApp

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: footballDataApp_macos
          path: ./footballDataApp_macos.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: footballDataApp
          path: .

      - name: Download macOS artifact
        uses: actions/download-artifact@v2
        with:
          name: footballDataApp_macos
          path: .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            ./footballDataApp.tar.gz
            ./footballDataApp_macos.tar.gz
